version: '2'

services:
  mariadbdariyals:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=dariyals_app
      - MARIADB_DATABASE=dariyals_base
  myappdariyals:
    image: docker.io/bitnami/laravel:8
    ports:
      - '9009:8000'
    environment:
      - DB_HOST=mariadbdariyals
      - DB_PORT=3306
      - DB_USERNAME=dariyals_app
      - DB_DATABASE=dariyals_base
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadbdariyals
